// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// logout
export const LOG_OUT = 'LOG_OUT';

// load dashboard data
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_RESPONSE = 'DASHBOARD_RESPONSE';
export const DASHBOARD_FAILED = 'DASHBOARD_FAILED';

// load transaction data
export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_RESPONSE = 'TRANSACTION_RESPONSE';
export const TRANSACTION_FAILED = 'TRANSACTION_FAILED';

// update transaction data
export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_RESPONSE = 'UPDATE_TRANSACTION_RESPONSE';
export const UPDATE_TRANSACTION_FAILED = 'UPDATE_TRANSACTION_FAILED';

// delete transaction data
export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_RESPONSE = 'DELETE_TRANSACTION_RESPONSE';
export const DELETE_TRANSACTION_FAILED = 'DELETE_TRANSACTION_FAILED';
export const DELETE_ALL_TRANSACTION_REQUEST = 'DELETE_ALL_TRANSACTION_REQUEST';
export const DELETE_ALL_TRANSACTION_RESPONSE = 'DELETE_ALL_TRANSACTION_RESPONSE';
export const DELETE_ALL_TRANSACTION_FAILED = 'DELETE_ALL_TRANSACTION_FAILED';

//get Currency User
export const GET_CURRENCY_RESPONSE = 'GET_CURRENCY_RESPONSE';

//update Curency User
export const UPDATECURRENCY_REQUEST = 'UPDATECURRENCY_REQUEST';
export const UPDATECURRENCY_RESPONSE = 'UPDATECURRENCY_RESPONSE';
export const UPDATECURRENCY_FAILED = 'UPDATECURRENCY_FAILED';

//update Wallet
export const UPDATEWALLET_REQUEST = 'UPDATEWALLET_REQUEST';
export const UPDATEWALLET_RESPONSE = 'UPDATEWALLET_RESPONSE';
export const UPDATEWALLET_FAILED = 'UPDATEWALLET_FAILED';

//add Wallet
export const ADD_WALLET_RESPONSE = 'ADD_WALLET_RESPONSE';

//delete Wallet
export const DELETEWALLET_REQUEST = 'DELETEWALLET_REQUEST';
export const DELETEWALLET_RESPONSE = 'DELETEWALLET_RESPONSE';
export const DELETEWALLET_FAILED = 'UPDATEWALLET_FAILED';

//loadmore
export const SET_TRANSACTION_FETCHING = 'SET_TRANSACTION_FETCHING';

//chart
export const CHART_ALL_WALLET_BY_MONTH_REQUEST = "CHART_ALL_WALLET_BY_MONTH_REQUEST";
export const CHART_ALL_WALLET_BY_MONTH_RESPONSE = "CHART_ALL_WALLET_BY_MONTH_RESPONSE";
export const CHART_ALL_WALLET_BY_MONTH_FAILED = "CHART_ALL_WALLET_BY_MONTH_FAILED";

export const CHART_ALL_WALLET_BY_YEAR_REQUEST = "CHART_ALL_WALLET_BY_YEAR_REQUEST";
export const CHART_ALL_WALLET_BY_YEAR_RESPONSE = "CHART_ALL_WALLET_BY_YEAR_RESPONSE";
export const CHART_ALL_WALLET_BY_YEAR_FAILED = "CHART_ALL_WALLET_BY_YEAR_FAILED";

//detail chart
export const DETAIL_CHART_WALLET_BY_MONTH_REQUEST = "DETAIL_CHART_WALLET_BY_MONTH_REQUEST"
export const DETAIL_CHART_WALLET_BY_MONTH_RESPONSE = "DETAIL_CHART_WALLET_BY_MONTH_RESPONSE"
export const DETAIL_CHART_WALLET_BY_MONTH_FAILED= "DETAIL_CHART_WALLET_BY_MONTH_FAILED"
