export const IMAGE_ICON: any = {
  cash: require("./Cash.png"),
  bankAccount: require("./BankAccount.png"),
  creditCard: require("./CreditCard.png"),
  debitCard: require("./DebitCard.png"),
  eWallet: require("./EWallet.png"),
  tShirt: require("./TShirt.png"),
  wallet: require("./Wallet.png"),
  food: require("./food.png"),
  shopping: require("./shopping.png"),
  housing: require("./housing.png"),
  transportation: require("./transportation.png"),
  lifeEntertainment: require("./lifeEntertainment.png"),
  financialExpenses: require("./financialExpenses.png"),
  income: require("./financialExpenses.png"),
  profileGuest: require("./ProfileGuest.png"),
  confuse: require("./Confuse.png"),
  arrowDown: require("./ic_arrow_down.png"),
};
